-- Sample data for BN Inmobiliaria
-- Run this in the Supabase SQL Editor to populate the database with sample properties

INSERT INTO properties (
  title,
  slug,
  description,
  price,
  currency,
  location_city,
  location_state,
  location_neighborhood,
  location_address,
  property_type,
  custom_bonuses,
  images,
  is_featured,
  display_order,
  near_beach,
  is_published,
  is_for_sale,
  is_for_rent,
  rent_price,
  rent_currency
) VALUES
(
  'Casa en Nuevo Salagua con Vista al Mar',
  'casa-nuevo-salagua-vista-mar',
  'Hermosa casa en Nuevo Salagua, Manzanillo con vista al mar, amplios espacios y acabados de lujo.',
  3500000,
  'MXN',
  'Manzanillo',
  'Colima',
  'Nuevo Salagua',
  'Av. Vista Hermosa 123',
  'casa',
  '["Cerca de la playa", "Vista al mar", "Barrio tranquilo", "Acceso a plazas comerciales"]'::jsonb,
  '["https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1600", "https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&w=1600", "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
  true,
  0,
  true,
  true,
  true,
  false,
  null,
  'MXN'
),
(
  'Departamento en Coto Alborada',
  'departamento-coto-alborada',
  'Moderno departamento en el exclusivo Coto Alborada con amenidades y seguridad 24/7.',
  2800000,
  'MXN',
  'Manzanillo',
  'Colima',
  'Fraccionamiento Mar de Plata',
  'Coto Alborada, Edificio B, Depto 301',
  'departamento',
  '["Amenidades", "Zona segura", "Cerca del mar"]'::jsonb,
  '["https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1600", "https://images.pexels.com/photos/1750391/pexels-photo-1750391.jpeg?auto=compress&cs=tinysrgb&w=1600", "https://images.pexels.com/photos/209315/pexels-photo-209315.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
  false,
  1,
  false,
  true,
  true,
  false,
  null,
  'MXN'
);
