// This file is auto-generated by Supabase
// DO NOT EDIT MANUALLY - Run `npx supabase gen types typescript` to regenerate

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          id: string
          user_id: string | null
          action: string
          resource_type: string | null
          resource_id: string | null
          details: Json | null
          ip_address: unknown | null
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          action: string
          resource_type?: string | null
          resource_id?: string | null
          details?: Json | null
          ip_address?: unknown | null
          user_agent?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          action?: string
          resource_type?: string | null
          resource_id?: string | null
          details?: Json | null
          ip_address?: unknown | null
          user_agent?: string | null
          created_at?: string
        }
      }
      credits: {
        Row: {
          id: string
          user_id: string
          balance: number | null
          free_credits_remaining: number | null
          last_free_credit_reset: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          balance?: number | null
          free_credits_remaining?: number | null
          last_free_credit_reset?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          balance?: number | null
          free_credits_remaining?: number | null
          last_free_credit_reset?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      credit_transactions: {
        Row: {
          id: string
          user_id: string
          amount: number
          type: string
          description: string | null
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          amount: number
          type: string
          description?: string | null
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          amount?: number
          type?: string
          description?: string | null
          metadata?: Json | null
          created_at?: string
        }
      }
      invitation_tokens: {
        Row: {
          id: string
          token: string
          email: string | null
          created_by: string
          expires_at: string
          used_at: string | null
          used_by: string | null
          trial_days: number | null
          created_at: string
          notes: string | null
        }
        Insert: {
          id?: string
          token: string
          email?: string | null
          created_by: string
          expires_at: string
          used_at?: string | null
          used_by?: string | null
          trial_days?: number | null
          created_at?: string
          notes?: string | null
        }
        Update: {
          id?: string
          token?: string
          email?: string | null
          created_by?: string
          expires_at?: string
          used_at?: string | null
          used_by?: string | null
          trial_days?: number | null
          created_at?: string
          notes?: string | null
        }
      }
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          phone_number: string | null
          whatsapp_number: string | null
          username: string | null
          company_name: string | null
          bio: string | null
          location: string | null
          profile_image: string | null
          cover_image: string | null
          is_visible: boolean | null
          onboarding_completed: boolean | null
          stripe_customer_id: string | null
          language_preference: string | null
          email_verified: boolean | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          phone_number?: string | null
          whatsapp_number?: string | null
          username?: string | null
          company_name?: string | null
          bio?: string | null
          location?: string | null
          profile_image?: string | null
          cover_image?: string | null
          is_visible?: boolean | null
          onboarding_completed?: boolean | null
          stripe_customer_id?: string | null
          language_preference?: string | null
          email_verified?: boolean | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          phone_number?: string | null
          whatsapp_number?: string | null
          username?: string | null
          company_name?: string | null
          bio?: string | null
          location?: string | null
          profile_image?: string | null
          cover_image?: string | null
          is_visible?: boolean | null
          onboarding_completed?: boolean | null
          stripe_customer_id?: string | null
          language_preference?: string | null
          email_verified?: boolean | null
          created_at?: string
          updated_at?: string
        }
      }
      properties: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          property_type: string
          price: number
          currency: string | null
          images: string[] | null
          videos: string[] | null
          status: string | null
          is_featured: boolean | null
          slug: string | null
          created_at: string | null
          updated_at: string | null
          display_order: number | null
          is_for_sale: boolean | null
          is_for_rent: boolean | null
          rent_price: number | null
          rent_currency: string | null
          location_city: string | null
          location_state: string | null
          location_neighborhood: string | null
          location_address: string | null
          location_lat: number | null
          location_lng: number | null
          show_map: boolean | null
          characteristics: Json | null
          custom_bonuses: Json | null
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          property_type: string
          price: number
          currency?: string | null
          images?: string[] | null
          videos?: string[] | null
          status?: string | null
          is_featured?: boolean | null
          slug?: string | null
          created_at?: string | null
          updated_at?: string | null
          display_order?: number | null
          is_for_sale?: boolean | null
          is_for_rent?: boolean | null
          rent_price?: number | null
          rent_currency?: string | null
          location_city?: string | null
          location_state?: string | null
          location_neighborhood?: string | null
          location_address?: string | null
          location_lat?: number | null
          location_lng?: number | null
          show_map?: boolean | null
          characteristics?: Json | null
          custom_bonuses?: Json | null
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          description?: string | null
          property_type?: string
          price?: number
          currency?: string | null
          images?: string[] | null
          videos?: string[] | null
          status?: string | null
          is_featured?: boolean | null
          slug?: string | null
          created_at?: string | null
          updated_at?: string | null
          display_order?: number | null
          is_for_sale?: boolean | null
          is_for_rent?: boolean | null
          rent_price?: number | null
          rent_currency?: string | null
          location_city?: string | null
          location_state?: string | null
          location_neighborhood?: string | null
          location_address?: string | null
          location_lat?: number | null
          location_lng?: number | null
          show_map?: boolean | null
          characteristics?: Json | null
          custom_bonuses?: Json | null
        }
      }
      property_drafts: {
        Row: {
          id: string
          user_id: string
          property_id: string | null
          form_data: Json
          current_step: string
          ai_text: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          property_id?: string | null
          form_data?: Json
          current_step?: string
          ai_text?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          property_id?: string | null
          form_data?: Json
          current_step?: string
          ai_text?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      property_leads: {
        Row: {
          id: string
          property_id: string
          user_id: string | null
          lead_type: string
          ip_address: unknown | null
          user_agent: string | null
          created_at: string
          metadata: Json | null
        }
        Insert: {
          id?: string
          property_id: string
          user_id?: string | null
          lead_type: string
          ip_address?: unknown | null
          user_agent?: string | null
          created_at?: string
          metadata?: Json | null
        }
        Update: {
          id?: string
          property_id?: string
          user_id?: string | null
          lead_type?: string
          ip_address?: unknown | null
          user_agent?: string | null
          created_at?: string
          metadata?: Json | null
        }
      }
      property_views: {
        Row: {
          id: string
          property_id: string
          user_id: string | null
          ip_address: unknown | null
          user_agent: string | null
          referrer: string | null
          viewed_at: string
          session_id: string | null
        }
        Insert: {
          id?: string
          property_id: string
          user_id?: string | null
          ip_address?: unknown | null
          user_agent?: string | null
          referrer?: string | null
          viewed_at?: string
          session_id?: string | null
        }
        Update: {
          id?: string
          property_id?: string
          user_id?: string | null
          ip_address?: unknown | null
          user_agent?: string | null
          referrer?: string | null
          viewed_at?: string
          session_id?: string | null
        }
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          stripe_subscription_id: string | null
          stripe_customer_id: string | null
          status: string | null
          plan_type: string | null
          trial_ends_at: string | null
          current_period_start: string | null
          current_period_end: string | null
          cancel_at_period_end: boolean | null
          canceled_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          stripe_subscription_id?: string | null
          stripe_customer_id?: string | null
          status?: string | null
          plan_type?: string | null
          trial_ends_at?: string | null
          current_period_start?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean | null
          canceled_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          stripe_subscription_id?: string | null
          stripe_customer_id?: string | null
          status?: string | null
          plan_type?: string | null
          trial_ends_at?: string | null
          current_period_start?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean | null
          canceled_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      user_roles: {
        Row: {
          id: string
          user_id: string
          role: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          role: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          role?: string
          created_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: {
      add_credits: {
        Args: {
          p_user_id: string
          p_amount: number
          p_type: string
          p_description?: string
        }
        Returns: boolean
      }
      deduct_credits: {
        Args: {
          p_user_id: string
          p_amount: number
          p_description?: string
        }
        Returns: boolean
      }
      get_agent_dashboard_stats: {
        Args: {
          agent_user_id?: string
        }
        Returns: {
          user_id: string
          total_properties: number
          active_properties: number
          total_views: number
          total_leads: number
          views_this_week: number
          leads_this_month: number
        }[]
      }
      get_subscription_status: {
        Args: {
          check_user_id: string
        }
        Returns: {
          status: string
          plan_type: string
          trial_ends_at: string
          current_period_end: string
          is_active: boolean
          stripe_subscription_id: string
          stripe_customer_id: string
        }[]
      }
      get_user_credits: {
        Args: {
          check_user_id: string
        }
        Returns: {
          balance: number
          free_credits_remaining: number
          last_free_credits_reset: string
        }[]
      }
      has_active_subscription: {
        Args: {
          check_user_id: string
        }
        Returns: boolean
      }
      has_role: {
        Args: {
          check_user_id: string
          check_role: string
        }
        Returns: boolean
      }
      use_invitation_token: {
        Args: {
          invite_token: string
          user_uuid: string
        }
        Returns: boolean
      }
      validate_invitation_token: {
        Args: {
          invite_token: string
        }
        Returns: {
          is_valid: boolean
          token_email: string
          token_trial_days: number
        }[]
      }
    }
    Enums: Record<string, never>
  }
}
